kind: pipeline
type: docker
name: deploy-bot

steps:
  - name: build-and-deploy
    image: appleboy/drone-docker
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker build -t asimogobot:latest .
      - docker stop asimogobot || true
      - docker rm asimogobot || true
      - docker run -d --name asimogobot -e BOT_TOKEN=${BOT_TOKEN} asimogobot:latest

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
