kind: pipeline
type: docker
name: deploy-bot

steps:
  - name: build-and-deploy
    image: docker:28-cli
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    environment:
      COMPOSE_PROJECT_NAME: "asimogobot"
      TZ: "Asia/Phnom_Penh"
      # ↓ 从 Drone secrets 注入 ↓
      BOT_TOKEN:
        from_secret: BOT_TOKEN
      BAIDU_APPID:
        from_secret: BAIDU_APPID
      BAIDU_SECRET:
        from_secret: BAIDU_SECRET
      DEEPSEEK_API_KEY:
        from_secret: DEEPSEEK_API_KEY
      FLOMO_WEBHOOK:
        from_secret: FLOMO_WEBHOOK
      NOTION_API_KEY:
        from_secret: NOTION_API_KEY
      NOTION_PAGE_ID:
        from_secret: NOTION_PAGE_ID
      REDIS_URL: "redis://192.168.0.105:6379"
    commands:
      - docker stop asimogobot || true
      - docker rm asimogobot || true
      #清理可能的重复容器
      - docker ps -a | grep asimogobot | awk '{print $1}' | xargs -r docker rm -f
        # 构建新镜像
      - docker build -t asimogobot:latest .

      - docker run -d --name asimogobot
        -e BOT_TOKEN=$$BOT_TOKEN
        -e BAIDU_APPID=$$BAIDU_APPID
        -e BAIDU_SECRET=$$BAIDU_SECRET
        -e DEEPSEEK_API_KEY=$$DEEPSEEK_API_KEY
        -e FLOMO_WEBHOOK=$$FLOMO_WEBHOOK
        -e NOTION_API_KEY=$$NOTION_API_KEY
        -e NOTION_PAGE_ID=$$NOTION_PAGE_ID
        -e REDIS_URL=$$REDIS_URL
        -e TZ=$$TZ
        --restart unless-stopped 
        asimogobot:latest
volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
  event:
    - push
