kind: pipeline
type: docker
name: deploy-bot

steps:
  - name: build-and-deploy
    image: docker:dind
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    environment:
      BOT_TOKEN:
        from_secret: BOT_TOKEN
      # 添加百度OCR相关的环境变量
      BAIDU_APPID:
        from_secret: BAIDU_APPID
      BAIDU_SECRET:
        from_secret: BAIDU_SECRET
      FLOMO_WEBHOOK:
        from_secret: FLOMO_WEBHOOK
      NOTION_API_KEY:
        from_secret: NOTION_API_KEY
      NOTION_PAGE_ID:
        from_secret: NOTION_PAGE_ID
      DEEPSEEK_API_KEY:
        from_secret: DEEPSEEK_API_KEY
            

    commands:
      # 确保停止所有旧容器实例测试
      - docker stop asimogobot || true
      - docker rm asimogobot || true
      # 清理可能的重复容器
      - docker ps -a | grep asimogobot | awk '{print $1}' | xargs -r docker rm -f
      # 构建新镜像
      - docker build -t asimogobot:latest .
      # 启动新容器，传递所有必要的环境变量
      - docker run -d --name asimogobot
        -e BOT_TOKEN=$$BOT_TOKEN
        -e BAIDU_APPID=$$BAIDU_APPID
        -e BAIDU_SECRET=$$BAIDU_SECRET
        -e DEEPSEEK_API_KEY=$$DEEPSEEK_API_KEY
        -e FLOMO_WEBHOOK=$$FLOMO_WEBHOOK
        -e NOTION_API_KEY=$$NOTION_API_KEY
        -e NOTION_PAGE_ID=$$NOTION_PAGE_ID
        asimogobot:latest

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
