kind: pipeline
type: docker
name: deploy-bot

steps:
  - name: build-and-deploy
    image: docker:dind
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    environment:
      COMPOSE_PROJECT_NAME: tg-bot-prod
      TZ: Asia/Phnom_Penh
      BOT_TOKEN:
        from_secret: BOT_TOKEN
      BAIDU_APPID:
        from_secret: BAIDU_APPID
      BAIDU_SECRET:
        from_secret: BAIDU_SECRET
      BAIDU_OCR_TOKEN:
        from_secret: BAIDU_OCR_TOKEN
      DEEPSEEK_API_KEY:
        from_secret: DEEPSEEK_API_KEY
      FLOMO_WEBHOOK:
        from_secret: FLOMO_WEBHOOK
      NOTION_API_KEY:
        from_secret: NOTION_API_KEY
      NOTION_PAGE_ID:
        from_secret: NOTION_PAGE_ID
      REDIS_URL: redis://192.168.0.105:6379
      NODE_ENV: production
    commands:
      # 安装 Docker Compose
      - apk add --no-cache bash curl python3 py3-pip
      - pip3 install docker-compose
      - docker-compose --version

      # 检查网络连通性
      - echo "🔍 检查网络连通性..."
      - ping -c 3 192.168.0.105

      # 创建环境变量文件
      - echo "🔧 创建环境变量文件..."
      - echo "BOT_TOKEN=$${BOT_TOKEN}" > .env
      - echo "DEEPSEEK_API_KEY=$${DEEPSEEK_API_KEY}" >> .env
      - echo "REDIS_URL=$${REDIS_URL}" >> .env
      - echo "NODE_ENV=$${NODE_ENV}" >> .env
      - echo "TZ=$${TZ}" >> .env
      - echo "BAIDU_APPID=$${BAIDU_APPID}" >> .env
      - echo "BAIDU_SECRET=$${BAIDU_SECRET}" >> .env
      - echo "BAIDU_OCR_TOKEN=$${BAIDU_OCR_TOKEN}" >> .env
      - echo "FLOMO_WEBHOOK=$${FLOMO_WEBHOOK}" >> .env
      - echo "NOTION_API_KEY=$${NOTION_API_KEY}" >> .env
      - echo "NOTION_PAGE_ID=$${NOTION_PAGE_ID}" >> .env

      # 验证环境变量文件
      - echo "📋 验证环境变量文件..."
      - cat .env | head -5

      # 停止旧服务
      - echo "🛑 停止旧服务..."
      - docker-compose -f docker-compose.prod.yml down --remove-orphans || true

      # 清理旧资源
      - echo "🧹 清理旧资源..."
      - docker system prune -f || true

      # 构建和部署服务
      - echo "🚀 构建和部署服务..."
      - docker-compose -f docker-compose.prod.yml build
      - docker-compose -f docker-compose.prod.yml up -d

      # 等待服务启动
      - echo "⏳ 等待服务启动..."
      - sleep 30

      # 检查服务状态
      - echo "🏥 检查服务状态..."
      - docker-compose -f docker-compose.prod.yml ps

      # 验证Bot容器
      - echo "✅ 验证Bot容器..."
      - docker-compose -f docker-compose.prod.yml exec -T bot node --version || echo "容器可能还在启动中"

      # 显示部署结果
      - echo "🎉 部署完成！"
      - docker-compose -f docker-compose.prod.yml logs --tail=10 bot

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
