kind: pipeline
type: docker
name: deploy-bot

steps:
  - name: build-and-deploy
    image: docker/compose:1.29.2
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    environment:
      COMPOSE_PROJECT_NAME: asimogoBot
      TZ: Asia/Phnom_Penh
      BOT_TOKEN:
        from_secret: BOT_TOKEN
      BAIDU_APPID:
        from_secret: BAIDU_APPID
      BAIDU_SECRET:
        from_secret: BAIDU_SECRET
      BAIDU_OCR_TOKEN:
        from_secret: BAIDU_OCR_TOKEN
      DEEPSEEK_API_KEY:
        from_secret: DEEPSEEK_API_KEY
      FLOMO_WEBHOOK:
        from_secret: FLOMO_WEBHOOK
      NOTION_API_KEY:
        from_secret: NOTION_API_KEY
      NOTION_PAGE_ID:
        from_secret: NOTION_PAGE_ID
      REDIS_URL: redis://192.168.0.105:6379
      NODE_ENV: production
    commands:
      - docker-compose version

      # 写入 .env（供 docker-compose.prod.yml 读取）
      - |
        cat > .env <<'EOF'
        BOT_TOKEN=${BOT_TOKEN}
        BAIDU_APPID=${BAIDU_APPID}
        BAIDU_SECRET=${BAIDU_SECRET}
        BAIDU_OCR_TOKEN=${BAIDU_OCR_TOKEN}
        DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
        FLOMO_WEBHOOK=${FLOMO_WEBHOOK}
        NOTION_API_KEY=${NOTION_API_KEY}
        NOTION_PAGE_ID=${NOTION_PAGE_ID}
        REDIS_URL=${REDIS_URL}
        NODE_ENV=${NODE_ENV}
        TZ=${TZ}
        EOF

      # 构建 + 启动 + 清理孤儿容器
      - docker-compose -f docker-compose.prod.yml up -d --build --remove-orphans

      # 基本状态与关键信息
      - docker-compose -f docker-compose.prod.yml ps
      - docker-compose -f docker-compose.prod.yml logs --tail=200 --no-color bot || true

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
  event:
    - push
