services:
  bot:
    container_name: asimogobot
    build:
      context: .
      target: production
    env_file:
      - .env
    environment:
      - TZ=Asia/Phnom_Penh
      - NODE_ENV=production
      - START_CMD=node --experimental-loader=./alias-loader.mjs dist/bot/bot.js # ← 新增
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('ok')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
