version: "3.8"

services:
  bot:
    image: 192.168.0.105:5000/telegram-bot:${IMAGE_TAG:-latest}
    container_name: telegram_bot_ci
    env_file:
      - .env
    restart: unless-stopped

    # 健康检查配置
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"

    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # 安全配置
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

    # 网络配置
    networks:
      - bot_network

    # 环境变量
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info

networks:
  bot_network:
    driver: bridge
